jobs:
  - name: deploy-nodecluster-jfrog_runCI
    type: runCI
    flags:
      - deploy-nodecluster-jfrog
    steps:
      - OUT: deploy-nodecluster-jfrog-appfile

  - name: deploy-nodecluster-jfrog-manifest
    type: manifest
    flags:
      - deploy-nodecluster-jfrog
    steps:
      - IN: nodecluster-jfrog-params
      - IN: deploy-nodecluster-jfrog-appfile

  - name: deploy-nodecluster-jfrog-deploy
    type: deploy
    flags:
      - deploy-nodecluster-jfrog
    steps:
      - IN: deploy-nodecluster-jfrog-manifest
      - IN: deploy-nodecluster-jfrog-cluster

      - TASK:
        - script: cd ~
        - script: tar zxf /tmp/shippable/$manifestName/$fileName/$fileName.tar.gz
        - script: forever stopall
        - script: forever start ./bin/www
