jobs:
  - name: deploy-nodecluster-basic_runCI
    type: runCI
    flags:
      - deploy-nodecluster-basic
    steps:
      - OUT: deploy-nodecluster-basic-appfile

  - name: deploy-nodecluster-basic-manifest
    type: manifest
    flags:
      - deploy-nodecluster-basic
    steps:
     - IN: deploy-nodecluster-basic-appfile

  - name: deploy-nodecluster-basic-deploy
    type: deploy
    flags:
      - deploy-nodecluster-basic
    steps:
      - IN: deploy-nodecluster-basic-manifest
      - IN: deploy-nodecluster-basic-cluster
      - TASK:
        - script: cd ~
        - script: tar zxf /tmp/shippable/$DEPLOYNODECLUSTERBASICMANIFEST_NAME/$DEPLOYNODECLUSTERBASICAPPFIL_NAME/
        - script: mkdir -p ~/$DEPLOYNODECLUSTERBASICAPPFIL_NAME && cd ~/$DEPLOYNODECLUSTERBASICAPPFIL_NAME
        - script: cd $DEPLOYNODECLUSTERBASICAPPFIL_NAME && nohup npm start &
