jobs:
  - name: deploy-nodecluster-basic_runCI
    type: runCI
    flags:
      - deploy-nodecluster-basic
    steps:
      - OUT: deploy-nodecluster-basic-appfile

  - name: deploy-nodecluster-basic-manifest
    type: manifest
    flags:
      - deploy-nodecluster-basic
    steps:
     - IN: deploy-nodecluster-basic-appfile

  - name: deploy-nodecluster-basic-deploy
    type: deploy
    flags:
      - deploy-nodecluster-basic
    steps:
      - IN: deploy-nodecluster-basic-manifest
      - IN: deploy-nodecluster-basic-cluster
      - IN: nodecluster-params
      - TASK:
        - script: cd ~
        - script: tar zxf /tmp/shippable/$manifestName/$fileName/$fileName.tar.gz
        - script: nohup npm start &
